version: '3.4'
services:

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    container_name: bottle-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      #- /etc/ssl/certs:/etc/ssl/certs:ro
      #- /etc/ssl/private:/etc/ssl/private:ro
    depends_on:
      - image-server
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
    restart: always

  image-server:
    build:
      context: ./
      dockerfile: Dockerfile.images
    container_name: image-server
    environment:
      - EXTERNAL_IP=institution.org
      - PYTHONUNBUFFERED=1
      - LANG=C.UTF-8
    volumes:
      - ./:/code
    command: ['uwsgi', '--plugin', '/usr/lib/uwsgi/plugins/python312_plugin.so','--ini', 'uwsgi.ini']

    restart: always

  mysql-images:
    restart: unless-stopped
    image: mysql:8
    container_name: mysql-images
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./data:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: 'redacted'
      MYSQL_DATABASE: 'images'
      TZ: America/Los_Angeles

    ports:
      - "3306:3306"
    expose:
      - 3306
